# Generated by Django 4.2.2 on 2023-06-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_addblog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
