# Generated by Django 4.2.2 on 2023-06-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_addblog_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Latestpost',
        ),
    ]
